### ISSUE TITLE
[Feature Request] Caculation permanence

### ISSUE THREAD

**Issue by otherfutures** [LiamRiddell/obsidian-solve#12]
**Is your feature request related to a problem? Please describe.**
One other request is to save the calculation output to the note if desired (or automatically for every case). Right now, if the app is either uninstalled or deactivated, the calculations also disappear &, in general, isn't saved to the `.md` file (unless of course, they've been manually copy & pasted). 

**Describe the solution you'd like**
A hotkey command & setting/config to print calculations as plaintext to the note file. Some possible states for this setting are: 

- on (for every case), 
- on (on demand/command), 
- off (app performs as it currently does). 

**Describe alternatives you've considered**
Just leave the add on as is, if you feel it's too much of an edge case.

**Comment by LiamRiddell** [comment]
@otherfutures I believe this should be closed by the work done in #32.
