### ISSUE TITLE
[Bug] Percentage Provider is Case Sensitive

### ISSUE THREAD

**Issue by FeralFlora** [LiamRiddell/obsidian-solve#21]
> 2\. `decrease 459.0 by 50%`.

This is case sensitive. `decrease` works, but `Decrease` doesn't.

_Originally posted by @FeralFlora in https://github.com/LiamRiddell/obsidian-solve/issues/20#issuecomment-1727248489_

**Comment by LiamRiddell** [comment]
Thank you for the report. Good spot! I'll get this sorted in the next release.
