### ISSUE TITLE
Support Alternate Date Formats

### ISSUE THREAD

**Issue by iamrecursion** [LiamRiddell/obsidian-solve#3]
I initially got pretty confused because my standard ISO date format was not being recognized. I understand that the use of `-` is technically an ambiguous parse with subtraction, but if you account for spacing this is solvable. 

Again, love the plugin so far!

**Comment by LiamRiddell** [comment]
Thank you again 😄 As mentioned once the plugin is approved and available through the Solve community plugins, I'm going to fix the existing Datetime provider. This will include the ability to select between three date formats.

1. European e.g. DD/MM/YYYY
2. American e.g. MM/DD/YYYY
3. ISO e.g. YYYY/MM/DD

This will be an option in the settings. This should really help over the current implementation.

**Comment by iamrecursion** [comment]
Oh that's awesome to hear! I think ISO is `YYYY-MM-DD` rather than using slashes, but in general yes!

**Comment by LiamRiddell** [comment]
> Oh that's awesome to hear! I think ISO is `YYYY-MM-DD` rather than using slashes, but in general yes!

You're right, we support `YYYY-MM-DD` in 0.4.0 release which is WIP. You can also substitute `-` with `.` or `/` as well :)

**Comment by iamrecursion** [comment]
Oh, awesome! I look forward to the release of 0.4.0! I am sure it will kick butt!

**Comment by LiamRiddell** [comment]
Fixed in #4

**Comment by iamrecursion** [comment]
Already making use of this one! Thank you so much!
