### ISSUE TITLE
[Feature Request] `logb(base, value)` for Arbitrary Bases

### ISSUE THREAD

**Issue by iamrecursion** [LiamRiddell/obsidian-solve#31]
**Is your feature request related to a problem? Please describe.**
I ran into a want for this today, and yes you can calculate it using multiple `ln`s but still!

**Describe the solution you'd like**
The suggested function implemented!

**Describe alternatives you've considered**

$\log_b(x) = \frac{\ln(x)}{\ln(b)}$

**Comment by LiamRiddell** [comment]
This is straightforward to implement. I've added to 0.7.0 (#29) release 👍

**Comment by iamrecursion** [comment]
Oh thank you so much!
