### ISSUE TITLE
[Feature Request] Commit Function

### ISSUE THREAD

**Issue by iamrecursion** [LiamRiddell/obsidian-solve#32]
**Is your feature request related to a problem? Please describe.**
Sometimes I use solve as a calculator for values I then want to be embedded into the rendered (reading mode) note. I currently just read them and then type over it.

**Describe the solution you'd like**
It would be great to have a command that commits the evaluation on the cursor line into the markdown text directly for this.

**Describe alternatives you've considered**
Allow solve preview to work in reading mode as well.

**Comment by LiamRiddell** [comment]
Hello, This will be releasing with 0.7.0 today! You can now hover the result and click it to commit the result to the document:

![image](https://i.gyazo.com/606d192fdaa092030102aaf4807c18e2.gif)

It's a the first revision of this feature. 😄

**Comment by iamrecursion** [comment]
Is there a command for doing this as well? I tend to interact without my mouse a lot, so being able to do this from the keyboard would be killer!

**Comment by iamrecursion** [comment]
But also thank you _so_ much! This will enhance the way I use solve no end!!

**Comment by LiamRiddell** [comment]
> Is there a command for doing this as well? I tend to interact without my mouse a lot, so being able to do this from the keyboard would be killer!

I'll see what I can do regarding the command. And, thank you very much for supporting the project 🥇

**Comment by LiamRiddell** [comment]
Hello, I've added two commands which should provide the functionality you may need;

1. Commit the result on the current line
2. Commit all visible results

You can see an example of number one:

![Solve Commit Commands](https://i.gyazo.com/662bbddf7500c397794f1ce5e6b4f779.gif)

**Comment by iamrecursion** [comment]
Awesome, thank you so much!

**Comment by darrylnoakes** [comment]
How about a command to commit all results in the selected text? I often have situations where I would want to commit a whole lot of results, but not everything.

**Comment by LiamRiddell** [comment]
> How about a command to commit all results in the selected text? I often have situations where I would want to commit a whole lot of results, but not everything.

Interesting use case, I'll see if it's possible!

**Comment by LiamRiddell** [comment]
@darrylnoakes I've implemented your suggestion but will probably go out with some optimisations in 0.9.0.
