### ISSUE TITLE
[Feature Request] Add comment to end of calculation

### ISSUE THREAD

**Issue by roaet** [LiamRiddell/obsidian-solve#35]
Just being able to label calculations. Although I can see just putting the comment one line above. Would be nice!

```
2000 - 100 # bubblegum
```

**Comment by LiamRiddell** [comment]
@roaet Hey, thank you for a good feature request! I'm going to rewrite the processing pipeline to allow for above by increasing it's modularity 👍 I'll aim to get this in `0.8.0` release.

**Comment by roaet** [comment]
YAAAAY
