### ISSUE TITLE
[Bug] Typo in the default date

### ISSUE THREAD

**Issue by eb2ai** [LiamRiddell/obsidian-solve#36]
**Describe the bug**
The default date output is `YYYY-MM-DDTHH:mm:ssZ`
I don't think you want that T in there.
![image](https://github.com/LiamRiddell/obsidian-solve/assets/134644662/c44e794e-52e1-4693-b94e-12c40134f88f)

**Comment by LiamRiddell** [comment]
@eb2ai Great spot, I'll get that sorted.

**Comment by eb2ai** [comment]
My bad. Thanks
