### ISSUE TITLE
[Feature Request] Support Solving Within Unit Conversions

### ISSUE THREAD

**Issue by iamrecursion** [LiamRiddell/obsidian-solve#41]
**Is your feature request related to a problem? Please describe.**
I often want to be able to do computations on some units and then convert them to another unit (e.g. `convert x lb - y oz to kg` or equivalently `x lb - y oz to kg`).

**Describe the solution you'd like**
For that to work in line.

**Describe alternatives you've considered**
Right now I end up doing the maths and then adding the conversion on a different line.

**Comment by LiamRiddell** [comment]
This was a challenge but it's complete and will be available in 0.9.0!

**Comment by iamrecursion** [comment]
Wonderful! Thank you so much, and thank you for being so _speedy_! Solve has become absolutely indispensable, and I love having it!
