### ISSUE TITLE
[Feature Request] Show result when declaring variables

### ISSUE THREAD

**Issue by Stakker** [LiamRiddell/obsidian-solve#44]
**Is your feature request related to a problem? Please describe.**

Now you have to declare variables separately before doing operations with them in order to see the results. I think this is a needlessly convoluted process. (Or I'm doing something wrong?)

For example, if I write this imaginary post-tax income calculation:

```
$monthly_net_income = 1000 * 0.7
$yearly_net_income = 12 * $monthly_net_income
```

The results are in those variables already, but I can't SEE them.

**Describe the solution you'd like**

So, I would like to see the value of the variable on the right like so:

```
$monthly_net_income = 1000 * 0.7                          700
$yearly_net_income = 12 * $monthly_net_income            8400
```

This way I have done the calculations and also declared the variables for further operations with only two lines.

This is BTW how Numi (https://numi.app) works, and if I remember correctly, also Soulver (https://soulver.app).

Thanks!

**Comment by LiamRiddell** [comment]
@Stakker Welcome to Solve community. Firstly, thank you for your feature request. You are using solve correctly 😄 This is a limitation in `<= 0.9.0`. However, in the `1.0.0` release I've added a setting that is turned on by default to show Solve results next to variables to be equal to Numi and Soulver 👍 

Side note - there will be a breaking change to variables in version `1.0.0` as the prefix will change from `$` to `:`. This is to resolve the conflict with MathJax expressions within obsidian. Your example would change to the following:

```
:monthly_net_income = 1000 * 0.7
:yearly_net_income = 12 * :monthly_net_income
```

I'll close the ticket as complete. Once again, thank you for the feature request and being part of making Solve a better plugin 💯

**Comment by Stakker** [comment]
This is great news, and thanks for making this *essential* plugin!
