### ISSUE TITLE
[Feature Request] User-definable decimal separator

### ISSUE THREAD

**Issue by esamecar** [LiamRiddell/obsidian-solve#46]
Hi,

I hope this is not a RTFM but I wish there was a way to set the decimal separator for non-english speaking users ("," instead of ".").

Thanks!

Marco

**Comment by LiamRiddell** [comment]
Thanks @esamecar, this is good feature request for making Solve for accessible for all. I'll look into this for `1.0.0`.

**Comment by LiamRiddell** [comment]
Tracking as part of #48. I'll now close this.
