### ISSUE TITLE
[Bug] Order on percentage multiplication

### ISSUE THREAD

**Issue by satler-git** [LiamRiddell/obsidian-solve#47]
**Describe the bug**
Here are two equation.
- `100 * 50%`
- `50% * 100`

The two equationshould be mathematically equal, but the answers do not match.

**To Reproduce**
1. Install this plugin.
2. Create new file.
3. Type `100 * 50%`.

**Expected behavior**
The answers are equal.

**Screenshots**
![image](https://github.com/LiamRiddell/obsidian-solve/assets/119724672/9295474e-e600-4f55-b1a2-0f23589c9adf)

**Obsidian**
- Version:0.9.0
- Platform: Desktop

**Comment by LiamRiddell** [comment]
Welcome @satler-git to the solve community 👋  thank you to your keen eye for spotting this bug. I'll create a fix for this that will go out in `1.0.0` release.

**Comment by LiamRiddell** [comment]
Hi @satler-git, Thanks for flagging this. It turns out a lot of the percentage logic was flawed. I've overhauled it and now results are matching Googles. Let's hope that's all sorted now. It will be released with the ongoing 1.0.0 release.
