### ISSUE TITLE
[Feature Request] YYYY-MM-DD Datetime Provider Parsing

### ISSUE THREAD

**Issue by deonjo** [LiamRiddell/obsidian-solve#50]
**Is your feature request related to a problem? Please describe.**
I think this plugin is awesome, and very snappy. I also like the time manipulation aspect. 
Currently I add today's date by using a shortcut cmd + d. and it will add the date as a YYYY-MM-DD format. I see that Solve can output in ISO format. But I was wondering if it could also parse as an ISO format. 

**Describe the solution you'd like**
It would be great if this could happen:
- add a default ISO date format to the list of European/American time parsing

Or what would be even more awesome is:
- regex parsing for Datetime Provider in the same format as the Datetime Result

**Screenshot of current behavior**
<img width="666" alt="Screenshot 2024-03-22 at 11 11 28 AM" src="https://github.com/LiamRiddell/obsidian-solve/assets/461874/99136e49-34ef-4d6e-8d92-9698f96283b7">

**Comment by LiamRiddell** [comment]
Hi @deonjo! Welcome to the solve community. Thank you for feature request. I'll need to take a look into this a bit further before commenting.

**Comment by LiamRiddell** [comment]
Hi, it looks like the issue was because your `2024-03-22` is being processed as arithmetic expression `2024 - 03 - 22`. I've added further improvements to the ISO datetime parser and bumped it's priority over the arithmetic provider. This should solve the above issue (I hope!).
