### ISSUE TITLE
Congrats on 1.0.0!

### ISSUE THREAD

**Issue by iamrecursion** [LiamRiddell/obsidian-solve#52]
Not an issue and please feel free to close it, but given the inability to start a discussion I wanted to say a _huge_ congratulations on the 1.0.0 release of Solve! There are so many features in 1.0.0, little and big, that I am absolutely going to get daily use out of!

**Comment by LiamRiddell** [comment]
Thanks @iamrecursion for the kind words. It's great to see people share the excitement for Solve!
