### ISSUE TITLE
[Bug] Inline Solve preview has incorrect span in list items

### ISSUE THREAD

**Issue by iamrecursion** [LiamRiddell/obsidian-solve#54]
**Describe the bug**
When using an inline solve in a list element, the span of the inline solve is offset incorrectly in preview, though the actual replacement works properly.

**To Reproduce**
1. Open an Obsidian note.
2. Insert the following text

```md
- Foo s`1 + 100`
```

3. It will appear as follows

```md
- Foo s`1 + 10 = 1010`
```

4. In particular the last zero is actually the final zero of the 100, not part of the answer. If you use a numbered list instead, the offset is two characters instead of one.

**Expected behavior**
The inline solve looks _normal_ in list items!

**Screenshots**

<img width="249" alt="image" src="https://github.com/LiamRiddell/obsidian-solve/assets/5780639/06bb87e6-cf46-4291-ac01-909116e4995c">

**Obsidian**
- Version: 1.0.1
- Platform: Desktop, Mobile

**Comment by LiamRiddell** [comment]
Hello! Thanks for reporting, that's a silly mistake from me. Rest assured I've fixed it and 1.0.2 patch has been released.

![image](https://github.com/LiamRiddell/obsidian-solve/assets/3812154/5a7430f4-bb58-4bbc-8c01-3673e4b112b1)

**Comment by iamrecursion** [comment]
Thanks so much, Liam! That was super quick and I can absolutely confirm the fix!
