### ISSUE TITLE
[Bug] Decimal places are ignored when using non-ENG decimal separator (",")

### ISSUE THREAD

**Issue by esamecar** [LiamRiddell/obsidian-solve#56]
**Describe the bug**
Calculation (sum) of floats with decimal separator set to non-ENG does not work. 

The decimal places are ignored if you use ",". That means the values after the separator are ignored and not used for calculation. 

Addition with numbers that contain a non-ENG thousands separator, which is used as a decimal separator in ENG ("."), on the other hand, leads to correct results, even if the separator is placed in the wrong position. It is therefore not used as a decimal separator, as desired.

**To Reproduce**

In plugin settings set `Decimal seperator` to `Non English` and use 2 `Decimal places`.

![CleanShot 2024-05-24 at 09 12 36](https://github.com/LiamRiddell/obsidian-solve/assets/4950719/814c3385-1af0-436b-87c0-a26dbf336b01)

![CleanShot 2024-05-24 at 09 12 19](https://github.com/LiamRiddell/obsidian-solve/assets/4950719/50f092f9-596e-4a9b-a939-f790e1ef4946)

In a note type

```
100 +3
100,4 + 3,4
100.4 + 3.4
```

**Expected behavior**

```
100 +3 = 103
100,4 + 3,4 = 103,8
100.4 + 3.4 = 1038
```

**Screenshots**
instead you get this:
![CleanShot 2024-05-24 at 09 11 51](https://github.com/LiamRiddell/obsidian-solve/assets/4950719/9e892765-5bf1-4d35-9507-6a20a575d0a8)

**Obsidian**
- Version: macOS
- Platform: Desktop

**Additional context**
Thanks for the awesome plugin.

**Comment by LiamRiddell** [comment]
Thank you for the clear and well structured big report. I'll look into this!

**Comment by guidokl** [comment]
Are there any updates on this? Can't get used to the period as decimal separator. 🙃

**Comment by Pedro-Cataneo** [comment]
> Are there any updates on this? Can't get used to the period as decimal separator. 🙃

Yeah, i just discovered this simple yet awesome plugin witch was exactly what i needed. But the decimal separator "," not working is killing me too.

**Comment by LiamRiddell** [comment]
Hi,

I'm going to attempt to push a fix for this soon. This is a difficult problem to solve as it requires interpreting numbers different and as numbers are the most core unit in Solve there is a massive blast radius for changes here. None the less here is the fix:

![image](https://github.com/user-attachments/assets/71483efe-c130-4d06-8142-ad2d19399d58)
