### ISSUE TITLE
[Feature Request] Show result when declaring variables if Explicit mode is ON

### ISSUE THREAD

**Issue by Dvornik** [LiamRiddell/obsidian-solve#60]
**Is your feature request related to a problem? Please describe.**
Ability to show the result when declaring variables if Explicit mode is ON. Now it is impossible to do it because the variable value is not assigned in this case:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/77f07631-dfa2-4fcf-aa2d-c2aeba78aeab">

**Describe the solution you'd like**
To make the variable value assignment not break if I need to output the value with an equals sign in Explicit mode

**Comment by LiamRiddell** [comment]
Thank you for spotting this @Dvornik. This was a major oversight on my part but now it led to a better implementation. Here is the fixed output:

![image](https://github.com/user-attachments/assets/a178b82a-87a3-4d83-9951-8c0e6f26f253)

This bug is resolved in #61
